export const TASK_LIST = [
  {
    id: "task-1",
    task: "Phone screen",
    completed: false,
    completionDate: "",
  },
  {
    id: "task-2",
    task: "Start tenant folder",
    completed: false,
    completionDate: "",
  },
  {
    id: "task-3",
    task: "Show property",
    completed: false,
    completionDate: "",
  },
  {
    id: "task-4",
    task: "Receive & review application",
    completed: false,
    completionDate: "",
  },
  {
    id: "task-5",
    task: "Collect application fee",
    completed: false,
    completionDate: "",
  },
  {
    id: "task-6",
    task: "Background, eviction, & credit check verification",
    completed: false,
    completionDate: "",
  },
  {
    id: "task-7",
    task: "Employment verification",
    completed: false,
    completionDate: "",
  },
  {
    id: "task-8",
    task: "Previous landlord references",
    completed: false,
    completionDate: "",
  },
  {
    id: "task-9",
    task: "Pet screening",
    completed: false,
    completionDate: "",
  },
  {
    id: "task-10",
    task: "Send acceptance / denial letter",
    completed: false,
    completionDate: "",
  },
  {
    id: "task-11",
    task: "Deposit to hold received & form completed",
    completed: false,
    completionDate: "",
  },
  {
    id: "task-12",
    task: "Schedule lease signing appointment",
    completed: false,
    completionDate: "",
  },
  {
    id: "task-13",
    task: "Sign lease - everyone over 18 y.o.",
    completed: false,
    completionDate: "",
  },
  {
    id: "task-14",
    task: "Sign addendums - rules & regulations, pet addendum, lead paint brochure",
    completed: false,
    completionDate: "",
  },
  {
    id: "task-15",
    task: "Move-in condition inspection & report",
    completed: false,
    completionDate: "",
  },
  {
    id: "task-16",
    task: "Receive security deposit, first month's rent, pet fees, etc. via certified funds",
    completed: false,
    completionDate: "",
  },
  {
    id: "task-17",
    task: "Receive copy of renter's insurance policy",
    completed: false,
    completionDate: "",
  },
  {
    id: "task-18",
    task: "Confirm utilities transferred to tenant",
    completed: false,
    completionDate: "",
  },
  {
    id: "task-19",
    task: "Set up tenant account in PM software",
    completed: false,
    completionDate: "",
  },
  {
    id: "task-20",
    task: "Give keys to tenant",
    completed: false,
    completionDate: "",
  },
];
